<?php

/**
 * @file
 * This file has different hooks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\shruthi_exercise\Event\UserLoginEvent;

/**
 * Implements hook_form_alter().
 */
function shruthi_exercise_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Gets called whenever form is opened.
  // Calling service to call getName func from CustomService.php.
  $data = \Drupal::service('custom_service')->getName();
  // Prints the value provided in the config form.
  print_r($data);
}

/**
 * Implements hook_theme().
 */
function shruthi_exercise_theme($existing, $type, $theme, $path) {

  return [
  // Name for the template file (html.twig)
    'shruthi_template' => [
  // Defined variables to be returned.
      'variables' => [
  // Can provide default value for markup here.
        'markup' => "",
  // Can prove default value for hexcode here.
        'hexcode' => "",
      ],
    ],
  ];

}

/**
 * Implements hook_user_login().
 */
function shruthi_exercise_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

/**
 * Implements hook_page_attachments_alter().
 */
function shruthi_exercise_page_attachments_alter(array &$attachments) {
  // Calling the service.
  $route_match = \Drupal::routeMatch();
  // Getting the route name of the particular page.
  $route_name = $route_match->getRouteName();
  // print_r($route_name);exit;
  // If the route name matches.
  if ($route_name === 'comment.admin') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'shruthi_exercise/css_lib';
  }
  // If the route name matches.
  elseif ($route_name === 'entity.node.canonical') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'shruthi_exercise/css_lib';
  }
}

