<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * implements hook_form_alter
 */

 function shruthi_exercise_form_alter(&$form,FormStateInterface $form_state, $form_id) {
    $data = \Drupal::service('custom_service')->getName();
    print_r($data);
  }
 /**
 * Implements hook_theme().
 */
function shruthi_exercise_theme($existing, $type, $theme, $path) {
#creates a theme in the controller
    return [
       'shruthi_template' => [
           'variables' => [
                'markup' => "",
                'hexcode'=> "",
            ],
       ],
   ];

 }